#!/bin/bash

[ X$1 == X ] && (
	echo "Usage: $0 <name>"
) && exit 1

NAME=$1
TITLE=proj_page/${NAME}.title
DESC=proj_page/${NAME}.desc
MARKD=proj_page/${NAME}.markdown

(
	[ ! -e ${TITLE} ] || \
	[ ! -e ${DESC} ] || \
	[ ! -e ${MARKD} ]
) && (
	echo "File not found!"
	echo "  ${TITLE}"
	echo "  ${DESC}"
	echo "  ${MARKD}"
) && exit 1

(
	cat << EOF
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>$(cat ${TITLE}) by lehmann7</title>
    <link rel="stylesheet" href="stylesheets/styles.css">
    <link rel="stylesheet" href="stylesheets/pygment_trac.css">
    <!--script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script-->
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!--[if lt IE 8]>
    <link rel="stylesheet" href="stylesheets/ie.css">
    <![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  </head>
  <body>
    <div id="header">
      <nav>
        <li class="fork"><a href="https://github.com/lehmann7">View On GitHub</a></li>
        <li class="downloads"><a href="https://github.com/lehmann7/${NAME}/zipball/master">ZIP</a></li>
        <li class="downloads"><a href="https://github.com/lehmann7/${NAME}/tarball/master">TAR</a></li>
      </nav>
    </div>

    <div class="wrapper">
      <section>
        <div id="title">
          <h1>$(cat ${TITLE})</h1>
          <p>$(cat ${DESC})</p>
          <hr>
          <span class="credits left">Project maintained by <a href="https://github.com/lehmann7">lehmann7</a></span>
          <span class="credits right">Hosted on GitHub Pages &mdash; Theme by <a href="https://twitter.com/michigangraham">mattgraham</a></span>
        </div>

       <div id="content">
$(markdown --html4tags ${MARKD})
       </div>
    </div>
    <!--[if !IE]><script>fixScale(document);</script><![endif]-->
  </body>
</html>
EOF
) > ${NAME}.html

